#!/usr/bin/with-contenv ash
# shellcheck shell=ash

set -euo pipefail

if [ -n "$PUID" ] && [ -n "$PGID" ] ; then

  if ! grep -qE "(^|:)$PGID:" /etc/group ; then
    addgroup -S "$PGID"
  fi

  if ! id "$PUID" > /dev/null 2>&1 ; then
    adduser -S "$PUID" -G "$PGID"
  fi

fi
