#!/usr/bin/with-contenv ash
# shellcheck shell=ash

set -euo pipefail

export NODE_OPTIONS="--unhandled-rejections=strict"

cmd="/tc66c-mqtt/index.js"

interval=""
if [ -n "$M_INTERVAL" ] ; then interval="yes" ; fi

loglevel=""
if [ -n "$LOG_LEVEL" ] ; then loglevel="yes" ; fi

if [ -n "$PUID" ] && [ -n "$PGID" ] ; then
  exec s6-setuidgid "$PUID:$PGID" "$cmd" "$TC66C_BLE_MAC" "$MQTT_BROKER" \
    ${interval:+ --interval "$M_INTERVAL"} \
    ${loglevel:+ --logLevel "$LOG_LEVEL"}
else
  exec "$cmd" "$TC66C_BLE_MAC" "$MQTT_BROKER" \
    ${interval:+ --interval "$M_INTERVAL"} \
    ${loglevel:+ --logLevel "$LOG_LEVEL"}
fi
