#!/usr/bin/with-contenv sh
# shellcheck shell=sh
# shellcheck disable=SC2086

# Disable globbing (to safely ignore SC2086)
set -f

export NODE_OPTIONS="--unhandled-rejections=strict"

cmd="/tc66c-mqtt/index.js"

if [ -n "$M_INTERVAL" ] ; then
  interval="--interval $M_INTERVAL"
fi

if [ -n "$LOG_LEVEL" ] ; then
  loglevel="--logLevel $LOG_LEVEL"
fi

if [ -n "$PUID" ] && [ -n "$PGID" ] ; then
  exec s6-setuidgid "$PUID:$PGID" "$cmd" "$TC66C_BLE_MAC" "$MQTT_BROKER" \
    $interval $loglevel
else
  exec "$cmd" "$TC66C_BLE_MAC" "$MQTT_BROKER" $interval $loglevel
fi
