name: Docker push

on:
  push:
    branches: ["main"]
    tags: ["**"]

jobs:
  push:
    name: Push to Docker Hub
    runs-on: ubuntu-20.04
    environment: docker-hub
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v3.0.2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1.1.0
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1.3.0
        with:
          install: true
      # Every commit to the main-branch gets published to Docker Hub tagged
      # under its commit-hash.
      - name: Build and push (main)
        if: github.ref == 'refs/heads/main'
        run: |
          docker build \
            --tag thijsputman/tc66c-mqtt:"${GITHUB_SHA:0:7}" \
            --platform linux/arm64/v8,linux/arm/v7,linux/amd64 \
            --push \
            .
      # Every tag created in Git is assumed to be a "named" release. It gets
      # published to Docker Hub under its commit-hash (potentially overwriting
      # the image created from the main-branch), as "latest", under its Git
      # tag-name (with the leading "v" removed in case the tag is a semantic
      # version, e.g. "v1.0.0" becomes "1.0.0"), as "stable" in case the
      # semantic version doesn't have any appendices (e.g. "1.0.0" is considered
      # stable, "1.0.0-beta1" not).
      - name: Build and push (tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ref=(${GITHUB_REF//\// })
          tag=${ref[2]}
          if [[ "$tag" =~ ^v[0-9]+\. ]] ; then
            tag=${tag:1}
          fi
          if [[ "$tag" =~ ^(latest|stable)$ ]]; then
            echo Tag \""$tag"\" is invalid!
            exit 1
          fi
          stable=()
          if [[ "$tag" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] ; then
            stable=(--tag thijsputman/tc66c-mqtt:stable)
          fi
          docker build \
            --tag thijsputman/tc66c-mqtt:"${GITHUB_SHA:0:7}" \
            --tag thijsputman/tc66c-mqtt:latest \
            --tag thijsputman/tc66c-mqtt:"$tag" "${stable[@]}" \
            --platform linux/arm64/v8,linux/arm/v7,linux/amd64 \
            --push \
            .
