name: Docker

on: [push]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Build image
        run: |
          docker build \
            --tag thijsputman/tc66c-mqtt:"${GITHUB_SHA:0:7}" \
            --output type=docker,dest=/tmp/buildx.tar \
            --platform linux/arm64 \
            .
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: buildx
          path: /tmp/buildx.tar
          retention-days: 5
  push_main:
    name: Push to Docker Hub (main)
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: production
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: buildx
          path: /tmp
      - name: Load and tag Docker image
        run: |
          docker load --input /tmp/buildx.tar
          docker tag thijsputman/tc66c-mqtt:"${GITHUB_SHA:0:7}" \
            thijsputman/tc66c-mqtt:latest
      - name: Push to Docker Hub
        run: |
          docker push --all-tags thijsputman/tc66c-mqtt
  push_tag:
    name: Push to Docker Hub (tag)
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    environment: production
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: buildx
          path: /tmp
      - name: Load and tag Docker image
        run: |
          ref=(${GITHUB_REF//\// })
          tag=${ref[2]}
          if [[ ${tag:0:1} == "v" ]] ; then
            tag=${tag:1}
          fi
          docker load --input /tmp/buildx.tar
          docker tag thijsputman/tc66c-mqtt:"${GITHUB_SHA:0:7}" \
            thijsputman/tc66c-mqtt:latest
          docker tag thijsputman/tc66c-mqtt:"${GITHUB_SHA:0:7}" \
            thijsputman/tc66c-mqtt:stable
          docker tag thijsputman/tc66c-mqtt:"${GITHUB_SHA:0:7}" \
            thijsputman/tc66c-mqtt:"$tag"
      - name: Push to Docker Hub
        run: |
          docker push --all-tags thijsputman/tc66c-mqtt
