name: Lint codebase

on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request:
    branches: [main]
jobs:
  lint:
    name: Lint codebase
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - name: Lint codebase
        uses: github/super-linter@v3.17.0
        env:
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          LINTER_RULES_PATH: .
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          JAVASCRIPT_DEFAULT_STYLE: prettier
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
